@host = https://oba-dogs-api.onrender.com

### Login to get JWT
# @name login
POST {{host}}/login
Content-Type: application/json

{
  "username": "owner@ong.com",
  "password": "a_very_strong_password"
}

@token = {{login.response.body.token}}

### Create a new dog (replace <token> with your JWT)
POST {{host}}/api/dogs
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Dog de Teste",
  "idade": 4,
  "sexo": "Masculino",
  "porte": "Médio",
  "raca": "Vira-lata",
  "especie": "Vira-lata"
}

### List all dogs
GET {{host}}/api/dogs

### Get dog by ID (replace 1 with actual ID)
GET {{host}}/api/dogs/1

### Upload an image to a dog (replace 1 with actual ID and <token> with your JWT)
PUT {{host}}/api/dogs/1/imagem
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="dog.jpg"
Content-Type: image/jpeg

< ./dog.jpg
--WebAppBoundary--

### Get dog image (replace 1 with actual ID)
GET {{host}}/api/dogs/1/imagem

### Create a new user (SUPER_ADMIN only)
POST {{host}}/api/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "user1@example.com",
  "password": "user1password",
  "role": "ADMIN"
}

### List all users
GET {{host}}/api/users
Authorization: Bearer {{token}}

### Get user by username
GET {{host}}/api/users/user1@example.com
Authorization: Bearer {{token}}
